//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vl.LeaveTracker.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LMSDbContext : DbContext
    {
        public LMSDbContext()
            : base("name=LMSDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EmployeeT> EmployeeTs { get; set; }
        public DbSet<LeaveT> LeaveTs { get; set; }
        public DbSet<MainT> MainTs { get; set; }
        public DbSet<ManagerT> ManagerTs { get; set; }
        public DbSet<StatusT> StatusTs { get; set; }
    }
}
