//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vl.LeaveTracker.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainT
    {
        public int LeaveId { get; set; }
        public int EmpId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public Nullable<System.DateTime> LeaveFrom { get; set; }
        public Nullable<System.DateTime> LeaveTo { get; set; }
        public string Reason { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
